image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  # @TODO remove token from here
  - docker login registry.gitlab.com -u olivierbeaulieu -p Ck8EyDwCLhNCtehS5Jyr

build:
  script:
    - docker-compose build
    - docker-compose push