version: '3'

services:
  # client:
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:c
  #     - 3000:3000
  #     - 9229:9229
  #   command: npm start
  
  tactician:
    build:
      context: .
    ports:
      - 3001:3001
      - 5000:5000
    volumes:
      - npm-cache:/root/.npm
  
  proxy:
    image: nginx
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80
    command: nginx -g 'daemon off;'

volumes:
  npm-cache:
    external: false